import { describe, expect, it } from 'vitest';

import {
  AUTOMATION_AUTHOR_EMAIL,
  existingReviewDisposition,
  metadataFreshnessBranch,
  validateAutomationOwnedBranch,
} from '../../scripts/open-metadata-freshness-pr.mjs';

describe('metadata freshness review branch safety', () => {
  it('creates a stable version-scoped automation branch', () => {
    expect(metadataFreshnessBranch('1.13.13')).toBe(
      'automation/metadata-freshness-1.13.13',
    );
    expect(() => metadataFreshnessBranch('next')).toThrow(/stable/u);
  });

  it('reuses an open review and respects a completed human decision', () => {
    expect(
      existingReviewDisposition([
        { number: 12, state: 'OPEN', url: 'https://example.test/12' },
      ]),
    ).toMatchObject({ action: 'reuse-open' });
    expect(
      existingReviewDisposition([
        { number: 11, state: 'CLOSED', url: 'https://example.test/11' },
      ]),
    ).toMatchObject({ action: 'respect-finished' });
    expect(existingReviewDisposition([])).toEqual({ action: 'create' });
  });

  it('only replaces an orphan branch generated by the workflow contract', () => {
    expect(() =>
      validateAutomationOwnedBranch({
        authors: [AUTOMATION_AUTHOR_EMAIL],
        changedPaths: [
          '.changeset/metadata-freshness.md',
          'docs/metadata-freshness-latest.md',
          'package.json',
          'packages/mui-phone-input/package.json',
          'pnpm-lock.yaml',
        ],
      }),
    ).not.toThrow();

    expect(() =>
      validateAutomationOwnedBranch({
        authors: ['maintainer@example.test'],
        changedPaths: ['package.json'],
      }),
    ).toThrow(/non-automation/u);
    expect(() =>
      validateAutomationOwnedBranch({
        authors: [AUTOMATION_AUTHOR_EMAIL],
        changedPaths: ['packages/mui-phone-input/src/index.ts'],
      }),
    ).toThrow(/outside the generated review contract/u);
  });
});
